/**
 * Build src/data/admissionsMasterList2026.js from the official Excel workbook.
 *
 *   node src/scripts/importAdmissionsMasterFromExcel.js
 *   node src/scripts/importAdmissionsMasterFromExcel.js --write
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import XLSX from 'xlsx';
import { mapCourseAndBranch } from '../data/admissionsCourseBranchMap2026.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const EXCEL_PATH = path.join(
  __dirname,
  '../../New Microsoft Office Excel Worksheet.xlsx'
);
const OUT_PATH = path.join(__dirname, '../data/admissionsMasterList2026.js');

const normalizeName = (v) =>
  String(v ?? '')
    .trim()
    .replace(/\s+/g, ' ');

const normalizePhone = (v) => {
  let d = String(v ?? '').replace(/\D/g, '');
  if (d.length === 11 && /^[6789]/.test(d)) d = d.slice(0, 10);
  return d.length >= 10 ? d.slice(-10) : d;
};

const toAdmissionNumber = (v) => {
  const s = String(v ?? '').trim();
  if (/^2026\d{4}$/.test(s)) return s;
  const n = Number(v);
  if (!Number.isNaN(n)) return `2026${String(Math.round(n)).slice(-4).padStart(4, '0')}`;
  return s;
};

const esc = (s) => String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'");

export function loadMasterRowsFromExcel(excelPath = EXCEL_PATH) {
  const wb = XLSX.readFile(excelPath);
  const sheet = wb.Sheets[wb.SheetNames[0]];
  const raw = XLSX.utils.sheet_to_json(sheet, { defval: '' });

  return raw.map((row) => ({
    admissionNumber: toAdmissionNumber(row['Admission No']),
    applicationNumber: String(row['Application No'] ?? '').trim(),
    studentName: normalizeName(row.Name).toUpperCase(),
    phone: normalizePhone(row['Contact No']),
    source: String(row.Quota ?? '').trim(),
    status: String(row.Status ?? 'Active').trim(),
    ...mapCourseAndBranch(row.Course, row.Branch),
    gender: String(row.Gender ?? '').trim(),
    caste: String(row.Caste ?? '').trim(),
    ews: String(row.EWS ?? '').trim(),
    reference1: String(row['Reference 1'] ?? '').trim(),
  }));
}

function renderMasterFile(rows) {
  const lines = rows.map(
    (r) =>
      `  { admissionNumber: '${esc(r.admissionNumber)}', applicationNumber: '${esc(r.applicationNumber)}', studentName: '${esc(r.studentName)}', phone: '${esc(r.phone)}', source: '${esc(r.source)}', status: '${esc(r.status)}', course: '${esc(r.course)}', branch: '${esc(r.branch)}' },`
  );
  return `/**
 * Official 2026 admission list (Admission No 20260001–20260056).
 * Source: New Microsoft Office Excel Worksheet.xlsx — regenerated by importAdmissionsMasterFromExcel.js
 * Admission No → admission_number + hall_ticket_number (NOT Application No).
 */
export const ADMISSIONS_MASTER_LIST_2026 = [
${lines.join('\n')}
];
`;
}

async function main() {
  const write = process.argv.includes('--write');
  const rows = loadMasterRowsFromExcel();
  console.log(JSON.stringify({ rowCount: rows.length, sample: rows.slice(0, 2) }, null, 2));

  if (write) {
    fs.writeFileSync(OUT_PATH, renderMasterFile(rows), 'utf8');
    console.log(`Wrote ${OUT_PATH}`);
  } else {
    console.log('Dry run — pass --write to update admissionsMasterList2026.js');
  }
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  main().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
